# Generated by Django 2.0.8 on 2018-08-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180823_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipante',
            name='ix_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.IX'),
        ),
        migrations.AddField(
            model_name='participante',
            name='ix_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', related_query_name='participante', to='core.IX'),
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together={('asn', 'ix_id')},
        ),
    ]
