# Generated by Django 2.0.8 on 2018-08-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180827_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='ix_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', related_query_name='participante', to='core.IX'),
        ),
    ]
