# Generated by Django 2.0.8 on 2018-08-31 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180827_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='boleto_url',
            field=models.CharField(blank=True, error_messages={'invalid': 'Insira uma url válida.'}, max_length=255, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_expiracao',
            field=models.DateField(),
        ),
    ]
