# Generated by Django 2.0.8 on 2018-09-21 21:35

from django.db import migrations, models
import invoice_api.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180831_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilparticipante',
            options={'ordering': ('uuid',), 'verbose_name': 'PerfilParticipante', 'verbose_name_plural': 'PerfisParticipantes'},
        ),
        migrations.AlterField(
            model_name='fatura',
            name='boleto_gerado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='encerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='id_financeiro',
            field=models.BigIntegerField(default=invoice_api.core.models.Fatura.auto_increment_id_financeiro),
        ),
    ]
