# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-04 17:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmap',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Organization'),
        ),
        migrations.AlterField(
            model_name='dioport',
            name='datacenter_position',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='dioport',
            name='ix_position',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='historicaldioport',
            name='datacenter_position',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='historicaldioport',
            name='ix_position',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='historicalphone',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalswitchmodule',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='switchmodule',
            name='model',
            field=models.CharField(max_length=255),
        ),
    ]
