# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 18:51
from __future__ import unicode_literals

from django.db import migrations, models


def update_tag_reserved_to_allocated(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    # Ref.: https://docs.djangoproject.com/en/1.11/topics/migrations/#data-migrations
    Tag = apps.get_model('core', 'Tag')
    Tag.objects.filter(status='RESERVED').update(status="ALLOCATED")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181004_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltag',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'available'), ('ALLOCATED', 'allocated'), ('PRODUCTION', 'production')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'available'), ('ALLOCATED', 'allocated'), ('PRODUCTION', 'production')], default='AVAILABLE', max_length=10),
        ),
        migrations.RunPython(update_tag_reserved_to_allocated),
    ]
