FROM python:3.5

COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

COPY ./compose/flask/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh
RUN chmod +x /start-dev.sh

RUN apt-get update
RUN apt-get install -y default-libmysqlclient-dev
RUN apt-get install -y whois
WORKDIR /app

