version: '2'

services:

  db:
    image: mariadb:10.3
    volumes:
      - ./mysql_data/:/mysql_data
      - ./etc/mysql/:/etc/mysql/
      - ./mysql_data/logs/mysql/:/var/log/mysql/
    environment:
      - MYSQL_USER=invoice_api
      - MYSQL_PASSWORD=EulerInvoiceMaker@18651
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
       - "3360:3360"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DESIGN=pepa-linha

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-django
    depends_on:
      - db
    command: /start.sh
    volumes:
      - .:/invoice_api
      - .:/media
    ports:
      - "9000:9000"
    links:
      - db
